model_list:
  - model_name: gpt-5
    litellm_params:
      model: gpt-5
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gemini-3-pro
    litellm_params:
      model: gemini/gemini-3-pro-preview
      api_key: os.environ/GEMINI_API_KEY # References the environment variable
  - model_name: gemini-2.5-flash-proxy
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY

general_settings:
  master_key: os.environ/MASTER_KEY
  user_header_name: "x-openwebui-user-email" # Use X-OpenWebUI-User-Email if you prefer email

user_header_mappings:
  - header_name: x-openwebui-user-id
    litellm_user_role: openwebui_user

# guardrails:
#   - guardrail_name: "presidio-pre-guard"
#     litellm_params:
#       guardrail: presidio # supported values: "aporia", "bedrock", "lakera", "presidio"
#       mode: "pre_call"
#       output_parse_pii: True

litellm_settings:
  extra_spend_tag_headers:
    - "x-openwebui-user-id"
    - "x-openwebui-user-email"
  # Sets a max budget of $X USD across all proxy calls
  max_budget: 50.0
  # Optional: Sets a duration for the budget to reset (e.g., 30 days)
  budget_duration: 30d
  success_callback: ["cost_and_usage_callback"]
